apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "nominatim.fullname" . }}-updates
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}-updates
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- if .Values.extraEnv }}
                  {{- include "common.tplvalues.render" (dict "value" .Values.extraEnv "context" $) | nindent 16 }}
                {{- end }}
                - name: PBF_URL
                  value: {{ .Values.PBF_URL | quote }}
                - name: REPLICATION_URL
                  value: {{ .Values.REPLICATION_URL | quote  }}
              command:
                - /bin/bash
                - -ec
                - |
                  sudo -u nominatim nominatim replication --project-dir /nominatim
          restartPolicy: Never
  schedule: "*/15 * * * *"
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit: 1